config/routes.rb
AuctionApp::Application.routes.draw do
  resources :users

  resources :auctions do 
    resources :bids
  end

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  has_many :bids, :dependent => :destroy
  belongs_to :seller, :class_name => "User"

  validates :title, :uniqueness => true
  validates :end_time, :presence => true
  validates :seller_id, :presence => true

  validate :end_time_in_the_future, :on => :update, :unless => :force_submit

  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  attr_accessor :force_submit

  def end_time_in_the_future
    errors.add(:end_time, "can't be in the past") if self.end_time && self.end_time < Time.now
  end

  def self.get_active_auctions
    where("end_time > ?", Time.now)
  end

  def highest_bid
    self.bids.maximum("amount")
  end

  def highest_bid_object
    self.bids.order(:amount => :desc).limit(1).first
  end

  def highest_bidder
    self.highest_bid_object.bidder if highest_bid_object
  end

  def closed?
    self.end_time < Time.now
  end
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :bidder, :class_name => "User"
  belongs_to :auction

  before_save :convert_bid_to_cents

  validate :higher_than_current?
  validates :amount, :numericality => true

  def convert_bid_to_cents
    self.amount = (self.amount*100).to_i
  end

  def amount_in_dollars
    self.amount/100.0
  end 

  def amount_in_cents
    self.amount*100
  end

  def higher_than_current?
    if !Bid.where("amount > ? AND auction_id = ?", amount_in_cents, self.auction.id).empty?
      errors.add(:amount, "is too low! It can't be lower than the current bid, sorry.")
    end  
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :listings, :class_name => "Auction", :foreign_key => "seller_id"
  has_many :bids, foreign_key: "bidder_id"

  has_secure_password

  validates_uniqueness_of :name, :message => "There is already a user with that name."

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  def to_s
    self.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user 
    @current_user ||= User.find_by(id: session["user_id"])
  end
  helper_method :current_user

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in. Log In."
      redirect_to login_path
    end
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :require_login, only: [:create, :update, :destroy]

  def index
    @auctions = Auction.get_active_auctions
  end

  def new 
    @auction = Auction.new
  end

  def create
    @auction = Auction.new(auction_params)
    @auction.seller = current_user
    if @auction.save
      redirect_to @auction 
    else 
      flash[:error] = @auction.errors.full_messages
      render 'new'
    end
  end

  def show 
    @auction = Auction.find(params[:id])
    @current_bidder = @auction.highest_bidder
  end

  def edit
    @auction = Auction.find(params[:id])
    if @auction.seller_id != current_user.id
      flash[:error] = "Please Log In As The Auction Owner To Update This Auction."
      redirect_to login_path
    else
      flash[:notice] = "Auction has ended, sorry!" if @auction.closed?
      render :edit
    end
  end

  def update
    @auction = Auction.find(params[:id])
     if @auction.seller_id == current_user.id
      if @auction.update(auction_params)
        flash[:notice] = "Auction successfully updated"
        redirect_to @auction
      else 
        flash[:error] = @auction.errors.full_messages
        render :edit   
      end
    else
      flash[:error] = "Please log in as the auction owner to update this auction."
      redirect_to login_path
    end
  end

  def destroy 
    @auction = Auction.find(params[:id])
    if @auction.seller_id == current_user.id
      if @auction.destroy
        redirect_to auctions_path, notice: "Successfully deleted auction. Sorry we're not sorry."
      else
        render 'edit'
      end
    else
      flash[:error] = "Please log in as the auction owner to delete this auction."
      redirect_to login_path
    end  
  end

  def end_auction
    @auction = Auction.find(params[:id])
    @auction.end_time = Time.now
    @auction.force_submit = true
    @auction.save
    flash[:notice] = "Successfully ended auction early."
    redirect_to auctions_path
  end

  private

  def auction_params
    params.require(:auction).permit(:title, :description, :end_time, :picture)
  end


end
                                                                                          

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :require_login, only: [:create]
  def index
    @auction = Auction.find(params[:auction_id])
    @bids = @auction.bids
  end

  def new
    @auction = Auction.find(params[:auction_id])
    @bid = Bid.new
  end

  def show 
    @bid = Bid.find(params[:id])
  end


  def create
    @auction = Auction.find(params[:auction_id])
    @bid = Bid.new(bid_params)
    @bid.bidder = current_user
    @bid.auction = @auction
    if not_users_own_auction?
      if @bid.save
        redirect_to @auction, :notice => "You are the current high bidder! Sorry!"
      else
        flash[:error] = @bid.errors.full_messages
        render :new
      end
    else
      flash[:error] = "You cannot bid on your own auction."
      redirect_to @auction
    end
  end

  private

  def bid_params
    params.require(:bid).permit(:amount)
  end

  def not_users_own_auction?
    @bid.auction.seller != current_user
  end
end
 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by(:name => params[:user][:name])
    if @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to auctions_path, :notice => "Successfully logged in!"
    else
      flash[:error] = "Name and password don't match."
      render :new
    end
  end

  def destroy 
    reset_session
    redirect_to auctions_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new 
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Successfully signed up!"
      redirect_to auctions_path 
    else 
      flash.now[:error] = @user.errors.full_messages

      render :new
    end
  end

  def show 
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper



end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuctionApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/auctions/_form.html.erb
<%= form_for @auction, html: {multipart: true, class: "form-horizontal"} do |f| %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :price, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :price %>
    </div>
  
  <div class="form-group">
    <%= f.label :closing_date, "End Date", :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.datetime_field :closing_date, :default => Date.today %>
      </div>
  </div>

  </div>
  <div class="form-group col-sm-2 control-label">
    <%= f.submit %>
  </div>

<% end %>

app/views/layouts/auctions/edit.html.erb
<% unless @auction.closed? %>
  <%= render "form" %>
<% end %>

<a href="/auctions/<%= @auction.id %>/end_auction">End Auction Early</a>
<% if @auction.closed? %>
  | <a href="/auctions/<%= @auction.id %>/delete">Delete Auction</a>
<% end %>

app/views/layouts/auctions/index.html.erb
<h1>Active Auctions</h1>
<div class="row">
  <% @auctions.each do |auction| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= image_tag(auction.picture(:thumb)) %>
        <div class="caption">
          <h3><%= link_to auction.title, auction %></h3>
          <h5><%= "Current highest bid: #{number_to_currency(auction.highest_bid / 100) if auction.highest_bid}" %></h5>
          <p><%= auction.description %></p>
          <p><%= auction.closing_date %></p>
          <p><%= link_to "bid", new_auction_bid_path(auction), class: "btn btn-primary" %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/auctions/new.html.erb
<%= render "form" %>

app/views/layouts/auctions/show.html.erb
<h2><%= @auction.title %></h2>
<p><%= image_tag @auction.picture.url(:medium) %></p>
<p><%= @auction.description %></p>
<p><%= @auction.end_time %></p>
<h3>Current Highest Bidder:</h3>
<p><%= @current_bidder %></p>
<p><%= "Auction has ended, sorry!" if @auction.closed? -%></p>
<p><%= number_to_currency(@auction.highest_bid/100) if @auction.highest_bid %></p>
<% if !@auction.closed? && @auction.end_time %>
  <p><%= time_ago_in_words(@auction.end_time)%> left</p>
<% end %>

app/views/layouts/bids/index.html.erb
<h2><%= link_to @auction.title, @auction %></h2>
<p><%= @auction.description %></p>

<% @bids.each do |bid| %>
  <% if bid.bidder %>
    <div>
      <%= bid.bidder.name %> bid
      <%= number_to_currency(bid.amount/100) %> at 
      <%= bid.created_at.strftime("%a, %B %e, %Y - %l:%m:%M %p") %>
    </div>
  <% end %>
<% end %>

app/views/layouts/bids/new.html.erb
<% if @auction.highest_bid %>
  <h4><%= "Current highest bid is #{@auction.highest_bid}" %></h4>
<% end %>

<%= form_for @bid, :url => auction_bids_path(@auction) do |f| %>

  <div>
  <%= f.label :amount %>
  <%= f.text_field :amount %>
  </div>
  <%= f.submit %>

<% end %>

app/views/layouts/users/new.html.erb
<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.text_field :password, :type => :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation, :type => :password %>
  </div>
  <%= f.submit %>

<% end %>

app/views/layouts/users/show.html.erb
<%= @user.name %>