auction/config/routes.rb
Rails.application.routes.draw do
  resources :bids
  resources :auctions_descriptions
  resources :open_auctions

end

auction/app/models/auctions_description.rb
class AuctionsDescription < ActiveRecord::Base
end

auction/app/models/bid.rb
class Bid < ActiveRecord::Base
end

auction/app/models/open_auction.rb
class OpenAuction < ActiveRecord::Base
end

auction/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

auction/app/controllers/auctions_descriptions_controller.rb
class AuctionsDescriptionsController < ApplicationController
  before_action :set_auctions_description, only: [:show, :edit, :update, :destroy]

  # GET /auctions_descriptions
  # GET /auctions_descriptions.json
  def index
    @auctions_descriptions = AuctionsDescription.all
  end

  # GET /auctions_descriptions/1
  # GET /auctions_descriptions/1.json
  def show
  end

  # GET /auctions_descriptions/new
  def new
    @auctions_description = AuctionsDescription.new
  end

  # GET /auctions_descriptions/1/edit
  def edit
  end

  # POST /auctions_descriptions
  # POST /auctions_descriptions.json
  def create
    @auctions_description = AuctionsDescription.new(auctions_description_params)

    respond_to do |format|
      if @auctions_description.save
        format.html { redirect_to @auctions_description, notice: 'Auctions description was successfully created.' }
        format.json { render :show, status: :created, location: @auctions_description }
      else
        format.html { render :new }
        format.json { render json: @auctions_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auctions_descriptions/1
  # PATCH/PUT /auctions_descriptions/1.json
  def update
    respond_to do |format|
      if @auctions_description.update(auctions_description_params)
        format.html { redirect_to @auctions_description, notice: 'Auctions description was successfully updated.' }
        format.json { render :show, status: :ok, location: @auctions_description }
      else
        format.html { render :edit }
        format.json { render json: @auctions_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions_descriptions/1
  # DELETE /auctions_descriptions/1.json
  def destroy
    @auctions_description.destroy
    respond_to do |format|
      format.html { redirect_to auctions_descriptions_url, notice: 'Auctions description was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auctions_description
      @auctions_description = AuctionsDescription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auctions_description_params
      params.require(:auctions_description).permit(:description, :currentprice, :end_date)
    end
end

auction/app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: [:show, :edit, :update, :destroy]

  # GET /bids
  # GET /bids.json
  def index
    @bids = Bid.all
  end

  # GET /bids/1
  # GET /bids/1.json
  def show
  end

  # GET /bids/new
  def new
    @bid = Bid.new
  end

  # GET /bids/1/edit
  def edit
  end

  # POST /bids
  # POST /bids.json
  def create
    @bid = Bid.new(bid_params)

    respond_to do |format|
      if @bid.save
        format.html { redirect_to @bid, notice: 'Bid was successfully created.' }
        format.json { render :show, status: :created, location: @bid }
      else
        format.html { render :new }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bids/1
  # PATCH/PUT /bids/1.json
  def update
    respond_to do |format|
      if @bid.update(bid_params)
        format.html { redirect_to @bid, notice: 'Bid was successfully updated.' }
        format.json { render :show, status: :ok, location: @bid }
      else
        format.html { render :edit }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1
  # DELETE /bids/1.json
  def destroy
    @bid.destroy
    respond_to do |format|
      format.html { redirect_to bids_url, notice: 'Bid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid
      @bid = Bid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bid_params
      params.require(:bid).permit(:amount)
    end
end

auction/app/controllers/open_auctions_controller.rb
class OpenAuctionsController < ApplicationController
  before_action :set_open_auction, only: [:show, :edit, :update, :destroy]

  # GET /open_auctions
  # GET /open_auctions.json
  def index
    @open_auctions = OpenAuction.all
  end

  # GET /open_auctions/1
  # GET /open_auctions/1.json
  def show
  end

  # GET /open_auctions/new
  def new
    @open_auction = OpenAuction.new
  end

  # GET /open_auctions/1/edit
  def edit
  end

  # POST /open_auctions
  # POST /open_auctions.json
  def create
    @open_auction = OpenAuction.new(open_auction_params)

    respond_to do |format|
      if @open_auction.save
        format.html { redirect_to @open_auction, notice: 'Open auction was successfully created.' }
        format.json { render :show, status: :created, location: @open_auction }
      else
        format.html { render :new }
        format.json { render json: @open_auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /open_auctions/1
  # PATCH/PUT /open_auctions/1.json
  def update
    respond_to do |format|
      if @open_auction.update(open_auction_params)
        format.html { redirect_to @open_auction, notice: 'Open auction was successfully updated.' }
        format.json { render :show, status: :ok, location: @open_auction }
      else
        format.html { render :edit }
        format.json { render json: @open_auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /open_auctions/1
  # DELETE /open_auctions/1.json
  def destroy
    @open_auction.destroy
    respond_to do |format|
      format.html { redirect_to open_auctions_url, notice: 'Open auction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_open_auction
      @open_auction = OpenAuction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def open_auction_params
      params.require(:open_auction).permit(:description, :price, :end_date)
    end
end

auction/app/helpers/application_helper.rb
module ApplicationHelper
end

auction/app/helpers/auctions_descriptions_helper.rb
module AuctionsDescriptionsHelper
end

auction/app/helpers/bids_helper.rb
module BidsHelper
end

auction/app/helpers/open_auctions_helper.rb
module OpenAuctionsHelper
end

auction/app/views/auctions_descriptions/_form.html.erb
<%= form_for(@auctions_description) do |f| %>
  <% if @auctions_description.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auctions_description.errors.count, "error") %> prohibited this auctions_description from being saved:</h2>

      <ul>
      <% @auctions_description.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :currentprice %><br>
    <%= f.text_field :currentprice %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

auction/app/views/auctions_descriptions/edit.html.erb
<h1>Editing Auctions Description</h1>

<%= render 'form' %>

<%= link_to 'Show', @auctions_description %> |
<%= link_to 'Back', auctions_descriptions_path %>

auction/app/views/auctions_descriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Auctions Descriptions</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Currentprice</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auctions_descriptions.each do |auctions_description| %>
      <tr>
        <td><%= auctions_description.description %></td>
        <td><%= auctions_description.currentprice %></td>
        <td><%= auctions_description.end_date %></td>
        <td><%= link_to 'Show', auctions_description %></td>
        <td><%= link_to 'Edit', edit_auctions_description_path(auctions_description) %></td>
        <td><%= link_to 'Destroy', auctions_description, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auctions description', new_auctions_description_path %>

auction/app/views/auctions_descriptions/new.html.erb
<h1>New Auctions Description</h1>

<%= render 'form' %>

<%= link_to 'Back', auctions_descriptions_path %>

auction/app/views/auctions_descriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @auctions_description.description %>
</p>

<p>
  <strong>Currentprice:</strong>
  <%= @auctions_description.currentprice %>
</p>

<p>
  <strong>End date:</strong>
  <%= @auctions_description.end_date %>
</p>

<%= link_to 'Edit', edit_auctions_description_path(@auctions_description) %> |
<%= link_to 'Back', auctions_descriptions_path %>

auction/app/views/bids/_form.html.erb
<%= form_for(@bid) do |f| %>
  <% if @bid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bid.errors.count, "error") %> prohibited this bid from being saved:</h2>

      <ul>
      <% @bid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

auction/app/views/bids/edit.html.erb
<h1>Editing Bid</h1>

<%= render 'form' %>

<%= link_to 'Show', @bid %> |
<%= link_to 'Back', bids_path %>

auction/app/views/bids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bids</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bids.each do |bid| %>
      <tr>
        <td><%= bid.amount %></td>
        <td><%= link_to 'Show', bid %></td>
        <td><%= link_to 'Edit', edit_bid_path(bid) %></td>
        <td><%= link_to 'Destroy', bid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bid', new_bid_path %>

auction/app/views/bids/new.html.erb
<h1>New Bid</h1>

<%= render 'form' %>

<%= link_to 'Back', bids_path %>

auction/app/views/bids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @bid.amount %>
</p>

<%= link_to 'Edit', edit_bid_path(@bid) %> |
<%= link_to 'Back', bids_path %>

auction/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auction</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

auction/app/views/open_auctions/_form.html.erb
<%= form_for(@open_auction) do |f| %>
  <% if @open_auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@open_auction.errors.count, "error") %> prohibited this open_auction from being saved:</h2>

      <ul>
      <% @open_auction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

auction/app/views/open_auctions/edit.html.erb
<h1>Editing Open Auction</h1>

<%= render 'form' %>

<%= link_to 'Show', @open_auction %> |
<%= link_to 'Back', open_auctions_path %>

auction/app/views/open_auctions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Open Auctions</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Price</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @open_auctions.each do |open_auction| %>
      <tr>
        <td><%= open_auction.description %></td>
        <td><%= open_auction.price %></td>
        <td><%= open_auction.end_date %></td>
        <td><%= link_to 'Show', open_auction %></td>
        <td><%= link_to 'Edit', edit_open_auction_path(open_auction) %></td>
        <td><%= link_to 'Destroy', open_auction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Open auction', new_open_auction_path %>

auction/app/views/open_auctions/new.html.erb
<h1>New Open Auction</h1>

<%= render 'form' %>

<%= link_to 'Back', open_auctions_path %>

auction/app/views/open_auctions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @open_auction.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @open_auction.price %>
</p>

<p>
  <strong>End date:</strong>
  <%= @open_auction.end_date %>
</p>

<%= link_to 'Edit', edit_open_auction_path(@open_auction) %> |
<%= link_to 'Back', open_auctions_path %>